FROM ubuntu:22.04
MAINTAINER george

RUN apt update && \
    apt install python3 python3-boto3 -y

WORKDIR /bist

COPY warp_Linux_x86_64.deb /bist/

RUN dpkg -i /bist/warp_Linux_x86_64.deb

COPY bist/ /bist/